//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPortal.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationPortal.MVC.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат email!.
        /// </summary>
        internal static string AccountEmailFormat {
            get {
                return ResourceManager.GetString("AccountEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать email!.
        /// </summary>
        internal static string AccountEmailNull {
            get {
                return ResourceManager.GetString("AccountEmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин должен быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string AccountLoginLength {
            get {
                return ResourceManager.GetString("AccountLoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать логин!.
        /// </summary>
        internal static string AccountLoginNull {
            get {
                return ResourceManager.GetString("AccountLoginNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин может содержать только символы A-Z, a-z, А-Я, а-я и символ \&quot;_\&quot;.
        /// </summary>
        internal static string AccountLoginUnallowableSymbols {
            get {
                return ResourceManager.GetString("AccountLoginUnallowableSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string AccountPasswordLength {
            get {
                return ResourceManager.GetString("AccountPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать пароль!.
        /// </summary>
        internal static string AccountPasswordNull {
            get {
                return ResourceManager.GetString("AccountPasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль может содержать только символы A-Z, a-z, А-Я, а-я и символ \&quot;_\&quot;.
        /// </summary>
        internal static string AccountPasswordUnallowableSymbols {
            get {
                return ResourceManager.GetString("AccountPasswordUnallowableSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный формат даты!.
        /// </summary>
        internal static string ArticlePublicationDateFormat {
            get {
                return ResourceManager.GetString("ArticlePublicationDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение даты!.
        /// </summary>
        internal static string ArticlePublicationDateValue {
            get {
                return ResourceManager.GetString("ArticlePublicationDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно указать сведения об авторах!.
        /// </summary>
        internal static string BookAuthorNamesEmpty {
            get {
                return ResourceManager.GetString("BookAuthorNamesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения о авторах должны занимать не более {0} символов!.
        /// </summary>
        internal static string BookAuthorNamesLength {
            get {
                return ResourceManager.GetString("BookAuthorNamesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат должен быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string BookFormatLength {
            get {
                return ResourceManager.GetString("BookFormatLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение количества страниц!.
        /// </summary>
        internal static string BookPageCountValue {
            get {
                return ResourceManager.GetString("BookPageCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение года издания!.
        /// </summary>
        internal static string BookPublishingYearValue {
            get {
                return ResourceManager.GetString("BookPublishingYearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL книги должен ссылаться на файл!.
        /// </summary>
        internal static string BookUrlExtension {
            get {
                return ResourceManager.GetString("BookUrlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание курса должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string CourseDescriptionLength {
            get {
                return ResourceManager.GetString("CourseDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название курса должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string CourseNameLength {
            get {
                return ResourceManager.GetString("CourseNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название материала должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string MaterialNameLength {
            get {
                return ResourceManager.GetString("MaterialNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный формат URL!.
        /// </summary>
        internal static string MaterialUrlFormat {
            get {
                return ResourceManager.GetString("MaterialUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неопознанный тип материала!.
        /// </summary>
        internal static string MaterialWrongType {
            get {
                return ResourceManager.GetString("MaterialWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название умения должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string SkillNameLength {
            get {
                return ResourceManager.GetString("SkillNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать название навыка!.
        /// </summary>
        internal static string SkillNameNull {
            get {
                return ResourceManager.GetString("SkillNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя может содержать только символы A-Z, a-z, А-Я, а-я и символ \&quot;_\&quot;.
        /// </summary>
        internal static string UserNameUnallowableSymbols {
            get {
                return ResourceManager.GetString("UserNameUnallowableSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное значение длительности видео!.
        /// </summary>
        internal static string VideoDurationValue {
            get {
                return ResourceManager.GetString("VideoDurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Качество видео должно быть длиной от {0} до {1} символов!.
        /// </summary>
        internal static string VideoQualityValue {
            get {
                return ResourceManager.GetString("VideoQualityValue", resourceCulture);
            }
        }
    }
}
