//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPortal.ConsoleUI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationPortal.ConsoleUI.Resources.OperationMessages", typeof(OperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изучены не все материалы курса!.
        /// </summary>
        internal static string AddCompletedCourseNotCompleted {
            get {
                return ResourceManager.GetString("AddCompletedCourseNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый курс успешно создан!.
        /// </summary>
        internal static string AddCourseSuccess {
            get {
                return ResourceManager.GetString("AddCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный курс уже содержит этот материал!.
        /// </summary>
        internal static string AddMaterialToCourseAlreadyExists {
            get {
                return ResourceManager.GetString("AddMaterialToCourseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал успешно добавлен к курсу!.
        /// </summary>
        internal static string AddMaterialToCourseSuccess {
            get {
                return ResourceManager.GetString("AddMaterialToCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс уже содержит такое умение!.
        /// </summary>
        internal static string AddSkillAlreadyExists {
            get {
                return ResourceManager.GetString("AddSkillAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навык успешно добавлен!.
        /// </summary>
        internal static string AddSkillSuccess {
            get {
                return ResourceManager.GetString("AddSkillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введенное имя пользователя, email или пароль!.
        /// </summary>
        internal static string AuthorizeWrongCredentials {
            get {
                return ResourceManager.GetString("AuthorizeWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не являетесь автором данного курса.
        /// </summary>
        internal static string CanEditCourseNotAnAuthor {
            get {
                return ResourceManager.GetString("CanEditCourseNotAnAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данного материала не существует!.
        /// </summary>
        internal static string CheckMaterialExistingNotFound {
            get {
                return ResourceManager.GetString("CheckMaterialExistingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже прошли данный курс!.
        /// </summary>
        internal static string CourseAlreadyCompleted {
            get {
                return ResourceManager.GetString("CourseAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс с таким именем уже существует!.
        /// </summary>
        internal static string CourseAlreadyExist {
            get {
                return ResourceManager.GetString("CourseAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже участник данного курса!.
        /// </summary>
        internal static string CourseAlreadyJoin {
            get {
                return ResourceManager.GetString("CourseAlreadyJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанного курса не существует!.
        /// </summary>
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не участвуете в этом курсе!.
        /// </summary>
        internal static string CourseNotJoined {
            get {
                return ResourceManager.GetString("CourseNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс успешно обновлен.
        /// </summary>
        internal static string EditCourseSuccess {
            get {
                return ResourceManager.GetString("EditCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список материалов пуст!.
        /// </summary>
        internal static string GetAllMaterialsEmptyResult {
            get {
                return ResourceManager.GetString("GetAllMaterialsEmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все материалы курса пройдены!.
        /// </summary>
        internal static string GetNextMaterialAnyNewMaterial {
            get {
                return ResourceManager.GetString("GetNextMaterialAnyNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось найти информацию о пользователе!.
        /// </summary>
        internal static string GetUserByIdNotFound {
            get {
                return ResourceManager.GetString("GetUserByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начато изучение нового курса!.
        /// </summary>
        internal static string JoinToCourseSuccess {
            get {
                return ResourceManager.GetString("JoinToCourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный Email уже занят!.
        /// </summary>
        internal static string RegisterEmailUsed {
            get {
                return ResourceManager.GetString("RegisterEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный логин уже занят!.
        /// </summary>
        internal static string RegisterLoginUsed {
            get {
                return ResourceManager.GetString("RegisterLoginUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пользователь зарегистрирован!.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У выбранного курса нет указанного умения!.
        /// </summary>
        internal static string RemoveSkillNotFound {
            get {
                return ResourceManager.GetString("RemoveSkillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навык успешно удален!.
        /// </summary>
        internal static string RemoveSkillSuccess {
            get {
                return ResourceManager.GetString("RemoveSkillSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанного пользователя не существует!.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
